//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VOTACIONES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Postulados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Postulados()
        {
            this.Votos = new HashSet<Votos>();
        }
    
        public int IdPostulado { get; set; }
        public string Nombre { get; set; }
        public string Propuestas { get; set; }
        public string Aptitudes { get; set; }
        public string Descripcion { get; set; }
        public string Jornada { get; set; }
        public string Foto { get; set; }
        public int CantidadVotos { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Votos> Votos { get; set; }
    }
}
