//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VOTACIONES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Votos
    {
        public int IdVoto { get; set; }
        public int IdAprendiz { get; set; }
        public Nullable<int> IdPostulado { get; set; }
        public Nullable<System.DateTime> FechaVoto { get; set; }
    
        public virtual Aprendiz Aprendiz { get; set; }
        public virtual Postulados Postulados { get; set; }
    }
}
